### ISSUE TITLE
Named capture groups should be converted correctly

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/windup-shim#81]
See example rule:
 
```
- category: mandatory
  customVariables:
  - name: class-name
    nameOfCaptureGroup: class-name
    pattern: org.hibernate.cfg.(?P<class-name>(AbstractPropertyHolder|AccessType))?
  description: |-
    Class {class-name} within the org.hibernate.cfg package has been moved
    This class within `org.hibernate.cfg` has been moved; see link for more information.
  effort: 1
  labels:
  - konveyor.io/target=hibernate6.2
  - konveyor.io/target=eap8
  - konveyor.io/source
  - hibernate
  links:
  - title: Hibernate 6 migration guide - API/SPI/Internal distinction
    url: https://docs.jboss.org/hibernate/orm/6.2/migration-guide/migration-guide.html#api-internal-cfg
  message: This class within `org.hibernate.cfg` has been moved; see link for more
    information.
  ruleID: hibernate-6.2-00040
````

In the above rule, `<class-name>` is invalid, regexp doesnt like "-" in variable name, we should convert these into camel case instead.
