### ISSUE TITLE
Error in some builtin rules: could not run grep with provided pattern exit status

### ISSUE THREAD

**Issue by pranavgaikwad** [konveyor/windup-shim#85]
Following rules result in this error

- component-changes-00019
- java-generic-information-00010
- xml-removed-components-00008
- os-specific-00001

It appears that in all these rules, the wildcard characters are interpreted as wildcards, but the intention is to escape them instead.

**Comment by jmle** [comment]
@pranavgaikwad is this still happening? I have checked for instance `java-generic-information-00010`, which in windup is
```xml
<filecontent pattern=".includeRoutes({*})" filename="{*}.java" />
```
and in konveyor
```yaml
    builtin.filecontent:
      filePattern: .*\.java
      pattern: .includeRoutes(.*)
```
and they look fine to me
